// src/components/navbar.svelte
<script>
	import Navmenu from './navmenu.svelte';
</script>

<nav class="flex items-center py-1.5">
	<!--<img class="mr-1.5 h-auto w-8 rounded-full"  height="64" width="64"/> */}-->
	<a href="/">
		<span class="text-xl font-bold">Home</span>
	</a>

	<div class="text-md ml-auto flex space-x-2 font-bold">
		<div>
			<a href="https://github.com/notmycode-labs" target="_blank" rel="noopener noreferrer">GitHub</a>
		</div>
		<div>
			<a href="/blog">Blog</a>
		</div>
		<div>
			<Navmenu />
		</div>
	</div>
</nav>

// src/components/Navbar.tsx
import Link from "next/link"

const Navbar = () => {
  return (
    <nav className="p-4">
      <div className="flex justify-between items-center">
        <div className="flex items-center">
          <Link href="/">Home</Link>
          <Link href="/" className="ml-4">
            About
          </Link>
        </div>
        <div className="flex items-center">
          <Link
            href="https://discord.notmycode.dev"
            target="_blank"
            rel="noopener noreferrer"
            className="mr-4 link"
          >
            Discord
          </Link>
          <Link
            href="https://github.com/notmycode-dev"
            target="_blank"
            rel="noopener noreferrer"
            className="link"
          >
            GitHub
          </Link>
        </div>
      </div>
    </nav>
  )
}

export default Navbar
